[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dead-reckoning"
version = "0.1.0"
description = "SIH 2026 - Problem 26168 - Deep Inertial Odometry"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "pandas",
    "numpy",
    "scipy",
    "onnx"
]

[tool.setuptools.packages.find]
where = ["src"]
